init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

validate:
	terraform validate

list:
	terraform state list

show:
	terraform state show ${uri}

clean:
	rm -rf .terraform*
	rm -f terraform.tfstate*